-- wirte a script to find outare of CIRCUMFERNCE OF CIRCLE
set serveroutput on
SET VERIFY OFF
SET FEEDBACK OFF
DECLARE
               PI CONSTANT NUMBER(3,2) :=3.14;
	CR NUMBER(5,2);
	RADIUS NUMBER(5);
BEGIN
	RADIUS := &RADIUS;
	CR := 2*PI*RADIUS;
	DBMS_OUTPUT.PUT_LINE('CIRCUMFERNCE OF CIRCLE'||'='||CR);
END;
/
SET SERVEROUTPUT OFF