

CREATE OR REPLACE PACKAGE BODY PK_1 AS
	PROCEDURE PRO_1(E_EID IN  NUMBER,GSAL OUT NUMBER)
	IS

	BEGIN
		SELECT BASICSAL*12 INTO GSAL FROM EMP WHERE EID=E_EID;
	END PRO_1;
	FUNCTION FUN_1(E_EID IN NUMBER)
	RETURN VARCHAR2
	IS
		CATEGORY VARCHAR2(50);
		GSAL NUMBER;
	BEGIN
		SELECT BASICSAL*12 INTO GSAL FROM EMP WHERE EID=E_EID;
		IF GSAL > 5000000 THEN
			CATEGORY:='HIGH INCOME EMPLOYEE';
		ELSE
			CATEGORY:='NORMAL INCOME EMPLOYEE';
		END IF;
		RETURN CATEGORY;
	END FUN_1;
END PK_1;
/