
/* Write a function that returns the age category of an employee.
Categories:
● Age < 18 → Minor
● 18–60 → Adult
● 60 → Senior */
SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION FUNC1(EMPID IN EMP.EID%TYPE)
RETURN VARCHAR2
IS
	F_CATEGORY VARCHAR2(20);
	F_AGE EMP.AGE%TYPE;
BEGIN
	SELECT AGE INTO F_AGE FROM EMP WHERE EID=EMPID;
	
	IF F_AGE < 18 THEN
		F_CATEGORY:='MINOR';
		RETURN F_CATEGORY;
	ELSIF F_AGE >= 18 AND F_AGE <= 60 THEN
		F_CATEGORY:='ADULT';
		RETURN F_CATEGORY;
	ELSE
		RETURN 'SENIOR';
	END IF;
END;
/
SET SERVEROUTPUT OFF

SELECT * FROM EMP;