/* 3. Write a program that prints value 1 to 100 number using WHILE LOOP
Command */

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

DECLARE 
	COUNTER NUMBER(5):=1;
BEGIN
	WHILE COUNTER <= 100 LOOP
		DBMS_OUTPUT.PUT_LINE(COUNTER);
		COUNTER := COUNTER +1;
	END LOOP;
END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
SET FEEDBACK ON