/* Write a PL/SQL block which converts temperature from Celsius to
Fahrenheit. */

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

ACCEPT C PROMPT "ENTER YOUR CHOICE 1.CONVERT Fahrenheit TO Celsius 2. convert  Celsius to Fahrenheit.";
	
DECLARE
	CHOICE NUMBER(5);
	CELSIUS NUMBER(10,5);
	FAHRENHEIT NUMBER(10,5);
BEGIN
	CHOICE:=&C;
	IF CHOICE=1 THEN
		FAHRENHEIT:=&FAHRENHEIT;
		CELSIUS:=(FAHRENHEIT-32)*5/9;
		DBMS_OUTPUT.PUT_LINE('CELSIUS' || CELSIUS);
	ELSIF CHOICE=2 THEN
		CELSIUS:=&CELSIUS;
		FAHRENHEIT:=(CELSIUS*(5/9))+32;
		DBMS_OUTPUT.PUT_LINE('FAHRENHEIT' || FAHRENHEIT);
	ELSE
		DBMS_OUTPUT.PUT_LINE('ENTER THE VALID CHOICE');
	END IF;
END;
/
SET SERVEROUTPUT OFF
SET VERIFY OFF
SET FEEDBACK OFF