/* Write a PL/SQL block which accepts measurement in feet and displays it
in cm, inch and meter. */

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

DECLARE

	V_FEET NUMBER;
	V_CM NUMBER;
	V_INCH NUMBER;
	V_METER NUMBER;
BEGIN

	V_FEET:=&ENTERFEET;
	V_CM:=V_FEET * 30.48;
	V_INCH:=V_FEET * 12;
	V_METER:=V_FEET * 0.3048;

	DBMS_OUTPUT.PUT_LINE('ENTER FEET IS'||V_FEET);
	DBMS_OUTPUT.PUT_LINE('ENTER CM IS'||V_CM);
	DBMS_OUTPUT.PUT_LINE('ENTER INCH IS'||V_INCH);
	DBMS_OUTPUT.PUT_LINE('ENTER METER IS'||V_METER);
END;
/
SET SERVEROUTPUT OFF
SET VERIFY OFF
SET FEEDBACK OFF