/*  Write a program that prints value 1 to 100 number using LOOP
Command */

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

DECLARE

	I NUMBER(5):=1;
BEGIN
	LOOP
		EXIT WHEN I>100;
		DBMS_OUTPUT.PUT_LINE(I);
		I:=I+1;
	END LOOP;

END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
SET FEEDBACK ON