/* ALL COMBINE ERROS  */ 
set serveroutput off
create or replace trigger tr_DATE
before insert or update or delete on NEWEMP
FOR EACH ROW
BEGIN
IF TRIM(TO_CHAR(SYSDATE, 'Day')) = 'Sunday' THEN
	RAISE_APPLICATION_ERROR (-20420,'YOU CAN NOT ACCESS TABLE ON SUNDAY');
END IF; 
IF TRIM(TO_CHAR(SYSDATE, 'HH'))<7 OR TRIM(TO_CHAR(SYSDATE, 'HH'))>17 THEN
	RAISE_APPLICATION_ERROR (-20420,'YOU CAN NOT ACCESS TABLE BEFORE 12 AM AND AFTER 5 PM');
END IF;
END;
/ 