--CALLING A PROCEDURE

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

DECLARE
	DEPTNO EMP.DEPTNO%TYPE;
	percentage NUMBER(5);
BEGIN
	DEPTNO:=&DEPTNO;
	percentage:=&percentage;
	pro_1(DEPTNO,percentage);
END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
SET FEEDBACK ON